spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mymariadb:3306/insurance
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties.hibernate:
      format_sql: true