spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insurance?serverTimezone=UTC&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
#    properties.hibernate:
#      format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
